from pathlib import Path
root=Path(__file__).resolve().parents[1]
p=root/'scripts'/'build_edgeiq_horse_performance_observation_fact_v1.py'
s=p.read_text(encoding='utf-8')
if 'REJECTION_PATH' not in s:
    s=s.replace("OUTPUT_PATH = (\n    DATA / \"edgeiq_horse_performance_observation_fact_v1.csv\"\n)\n", "OUTPUT_PATH = (\n    DATA / \"edgeiq_horse_performance_observation_fact_v1.csv\"\n)\n\nREJECTION_PATH = (\n    DATA / \"edgeiq_horse_performance_observation_fact_v1_rejections.csv\"\n)\n")
    s=s.replace("OUTPUT_FIELDS = [", "REJECTION_FIELDS = [\n    \"performance_rating_base_id\",\n    \"performance_normalisation_id\",\n    \"performance_intelligence_base_id\",\n    \"benchmark_observation_id\",\n    \"race_key\",\n    \"race_date\",\n    \"track_name\",\n    \"official_distance_metres\",\n    \"source_horse_name\",\n    \"rejection_reason\",\n    \"policy_version\",\n    \"built_at_utc\",\n]\n\nOUTPUT_FIELDS = [")
    s=s.replace("def atomic_write_csv(\n    path: Path,\n    rows: list[dict[str, object]],\n) -> None:", "def atomic_write_csv_with_fields(\n    path: Path,\n    rows: list[dict[str, object]],\n    fields: list[str],\n) -> None:")
    s=s.replace("fieldnames=OUTPUT_FIELDS,", "fieldnames=fields,")
    s=s.replace("def main() -> None:", "def atomic_write_csv(\n    path: Path,\n    rows: list[dict[str, object]],\n) -> None:\n    atomic_write_csv_with_fields(path, rows, OUTPUT_FIELDS)\n\n\ndef main() -> None:")
    s=s.replace("atomic_write_csv(OUTPUT_PATH, [])\n\n        print(", "atomic_write_csv(OUTPUT_PATH, [])\n        atomic_write_csv_with_fields(REJECTION_PATH, [], REJECTION_FIELDS)\n\n        print(")
    s=s.replace("if identity_fields != IDENTITY_FIELDS:\n        fail(\n            \"Horse identity-map fields do not match the governed \"\n            f\"schema. Actual: {identity_fields}\"\n        )", "missing_identity_fields = [field for field in IDENTITY_FIELDS if field not in identity_fields]\n    if missing_identity_fields:\n        fail(\n            \"Horse identity-map missing governed fields: \"\n            f\"{missing_identity_fields}. Actual: {identity_fields}\"\n        )")
    s=s.replace("output_rows: list[dict[str, object]] = []\n    seen_rating_ids", "output_rows: list[dict[str, object]] = []\n    rejection_rows: list[dict[str, object]] = []\n    seen_rating_ids")
    s=s.replace("if identity is None:\n            fail(\n                f\"{rating_id}: no approved exact horse identity \"\n                f\"for {source_horse_name!r}.\"\n            )", "if identity is None:\n            rejection_rows.append({\n                \"performance_rating_base_id\": rating_id,\n                \"performance_normalisation_id\": text(rating[\"performance_normalisation_id\"]),\n                \"performance_intelligence_base_id\": text(rating[\"performance_intelligence_base_id\"]),\n                \"benchmark_observation_id\": text(rating[\"benchmark_observation_id\"]),\n                \"race_key\": text(rating[\"race_key\"]),\n                \"race_date\": text(rating[\"race_date\"]),\n                \"track_name\": text(rating[\"track_name\"]),\n                \"official_distance_metres\": text(rating[\"official_distance_metres\"]),\n                \"source_horse_name\": source_horse_name,\n                \"rejection_reason\": \"NO_APPROVED_EXACT_HORSE_IDENTITY\",\n                \"policy_version\": \"RA-HORSE-ID-GOV-V4\",\n                \"built_at_utc\": built_at_utc,\n            })\n            continue")
    s=s.replace("atomic_write_csv(OUTPUT_PATH, output_rows)\n\n    print(", "atomic_write_csv(OUTPUT_PATH, output_rows)\n    atomic_write_csv_with_fields(REJECTION_PATH, rejection_rows, REJECTION_FIELDS)\n\n    print(")
    s=s.replace("f\"{len(output_rows)}\"\n    )\n    print(f\"output={OUTPUT_PATH}\")", "f\"{len(output_rows)}\"\n    )\n    print(f\"identity_rejection_rows={len(rejection_rows)}\")\n    print(f\"output={OUTPUT_PATH}\")")
p.write_text(s,encoding='utf-8')

ap=root/'scripts'/'audit_edgeiq_horse_performance_observation_fact_v1.py'
s=ap.read_text(encoding='utf-8')
if 'REJECTION_PATH' not in s:
    s=s.replace("FACT_PATH = (\n    DATA / \"edgeiq_horse_performance_observation_fact_v1.csv\"\n)\n", "FACT_PATH = (\n    DATA / \"edgeiq_horse_performance_observation_fact_v1.csv\"\n)\n\nREJECTION_PATH = (\n    DATA / \"edgeiq_horse_performance_observation_fact_v1_rejections.csv\"\n)\n")
    s=s.replace("_, rating_rows = read_csv(RATING_PATH)\n    fact_fields, fact_rows = read_csv(FACT_PATH)", "_, rating_rows = read_csv(RATING_PATH)\n    fact_fields, fact_rows = read_csv(FACT_PATH)\n    rejection_rows = []\n    if REJECTION_PATH.exists():\n        _, rejection_rows = read_csv(REJECTION_PATH)")
    s=s.replace("fact_rating_ids = [\n        text(row[\"performance_rating_base_id\"])\n        for row in fact_rows\n    ]", "fact_rating_ids = [\n        text(row[\"performance_rating_base_id\"])\n        for row in fact_rows\n    ]\n    rejected_rating_ids = [\n        text(row.get(\"performance_rating_base_id\"))\n        for row in rejection_rows\n    ]")
    s=s.replace("rating_ids == set(fact_rating_ids),\n        {\n            \"rating_rows\": len(rating_rows),\n            \"fact_rows\": len(fact_rows),\n            \"missing\": sorted(\n                rating_ids - set(fact_rating_ids)\n            ),\n            \"unexpected\": sorted(\n                set(fact_rating_ids) - rating_ids\n            ),", "rating_ids == set(fact_rating_ids).union(set(rejected_rating_ids)),\n        {\n            \"rating_rows\": len(rating_rows),\n            \"fact_rows\": len(fact_rows),\n            \"rejection_rows\": len(rejection_rows),\n            \"missing\": sorted(\n                rating_ids - set(fact_rating_ids).union(set(rejected_rating_ids))\n            ),\n            \"unexpected\": sorted(\n                set(fact_rating_ids).union(set(rejected_rating_ids)) - rating_ids\n            ),")
    s=s.replace('"horse_performance_observation_rows": len(fact_rows),\n            "identity_map_rows": len(identity_rows),\n            "performance_rating_base_rows": len(rating_rows),', '"horse_performance_observation_rows": len(fact_rows),\n            "identity_rejection_rows": len(rejection_rows),\n            "identity_map_rows": len(identity_rows),\n            "performance_rating_base_rows": len(rating_rows),')
    s=s.replace('"horse_performance_observation_rows": len(fact_rows),\n            "identity_map_rows": len(identity_rows),\n            "performance_rating_base_rows": len(rating_rows),', '"horse_performance_observation_rows": len(fact_rows),\n            "identity_rejection_rows": len(rejection_rows),\n            "identity_map_rows": len(identity_rows),\n            "performance_rating_base_rows": len(rating_rows),')
ap.write_text(s,encoding='utf-8')
print('V4 scripts and partial-safe observation patch written')
