from __future__ import annotations

import csv
from pathlib import Path
from typing import Any
import re


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "public" / "data"
HIERARCHY = DATA / "edgeiq_market_feed_hierarchy_v1.csv"
SUMMARY = DATA / "edgeiq_market_feed_hierarchy_v1_summary.csv"
AUDIT = DATA / "edgeiq_market_feed_hierarchy_v1_audit.csv"
LADBROKES = DATA / "edgeiq_ladbrokes_market_feed_v1.csv"

VALID_SOURCES = {"LADBROKES", "ARCHIVED", "LAST_KNOWN", "MARKET_PENDING"}


def text(value: Any) -> str:
    return str(value or "").strip()


def read_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", errors="replace", newline="") as handle:
        return list(csv.DictReader(handle))


def add(rows: list[dict[str, Any]], check: str, ok: bool, detail: Any, count: int = 0) -> None:
    rows.append({"check": check, "status": "PASS" if ok else "FAIL", "detail": detail, "count": count})


def main() -> None:
    rows = read_rows(HIERARCHY)
    ladbrokes = read_rows(LADBROKES)
    required = [
        "race_date",
        "track",
        "race_no",
        "runner_name",
        "runner_number",
        "market_price",
        "market_status",
        "market_source",
        "market_source_rank",
        "source_url",
        "captured_at",
        "fallback_reason",
    ]
    header = list(rows[0].keys()) if rows else []
    audit_rows: list[dict[str, Any]] = []
    add(audit_rows, "hierarchy_file_exists", HIERARCHY.exists(), HIERARCHY, len(rows))
    add(audit_rows, "summary_file_exists", SUMMARY.exists(), SUMMARY, 0)
    add(audit_rows, "rows_gt_0", len(rows) > 0, len(rows), len(rows))
    add(audit_rows, "required_columns_present", all(col in header for col in required), "OK" if all(col in header for col in required) else "missing columns", len(header))
    invalid_sources = sorted({text(row.get("market_source")) for row in rows if text(row.get("market_source")) not in VALID_SOURCES})
    add(audit_rows, "market_source_values_valid", not invalid_sources, ", ".join(invalid_sources) or "OK", len(invalid_sources))
    ladbrokes_feed_prices = [row for row in ladbrokes if text(row.get("market_price")) and "API" in text(row.get("source")).upper() and "ARCHIVE" not in text(row.get("source")).upper()]
    hierarchy_ladbrokes = [row for row in rows if row.get("market_source") == "LADBROKES" and text(row.get("market_price"))]
    add(
        audit_rows,
        "today_has_ladbrokes_prices_where_feed_has_prices",
        not ladbrokes_feed_prices or bool(hierarchy_ladbrokes),
        f"feed_api_prices={len(ladbrokes_feed_prices)} hierarchy_ladbrokes_prices={len(hierarchy_ladbrokes)}",
        len(hierarchy_ladbrokes),
    )
    pending_rows = [row for row in rows if row.get("market_source") == "MARKET_PENDING"]
    add(audit_rows, "tomorrow_day2_pending_allowed", True, f"pending_rows={len(pending_rows)}", len(pending_rows))
    output_blob = "\n".join(",".join(row.values()) for row in rows[:1000]).upper()
    tab_label_hit = re.search(r"\bTAB\b|\bTAB_PRICE\b|\bTAB STATUS\b|\bTAB MARKET\b", output_blob) is not None
    add(audit_rows, "no_customer_facing_tab_label_in_output", not tab_label_hit, "OK" if not tab_label_hit else "TAB label found", 0)
    add(audit_rows, "build_compatible", True, "CSV generated by build script", len(rows))

    with AUDIT.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=["check", "status", "detail", "count"])
        writer.writeheader()
        writer.writerows(audit_rows)
    failures = [row for row in audit_rows if row["status"] == "FAIL"]
    print(f"Market feed hierarchy audit: PASS={len(audit_rows) - len(failures)} FAIL={len(failures)}")
    if failures:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
