from edgeiq_weather_victoria_common_v1 import *
alias=json.loads((DOCS_BOM/'edgeiq_victorian_track_alias_audit_v1.json').read_text(encoding='utf-8')) if (DOCS_BOM/'edgeiq_victorian_track_alias_audit_v1.json').exists() else {}
sel=read_csv(DOCS_BOM/'edgeiq_victorian_track_bom_station_selection_v1.csv')
weather=json.loads((PUBLIC/'edgeiq_victorian_track_weather_v1.json').read_text(encoding='utf-8')) if (PUBLIC/'edgeiq_victorian_track_weather_v1.json').exists() else {'records':[]}
rec=weather.get('records',[])
manual=[r for r in sel if r.get('approval_status') not in {'AUTO_APPROVED_DIRECT_LOCAL','AUTO_APPROVED_NEARBY_REPRESENTATIVE'}]
metrics={'tracks_supplied':len(IN_SCOPE)+len(DIRECT),'tracks_normalised':alias.get('represented_identities',0),'direct_source_tracks':len(DIRECT),'bom_assignment_tracks':len(IN_SCOPE),'fixed_stations_selected':sum(bool(r.get('selected_station_id')) and r.get('approval_status')=='AUTO_APPROVED_NEARBY_REPRESENTATIVE' for r in sel),'regional_proxies_selected':0,'manual_review_mappings':len(manual),'unresolved_mappings':sum(r.get('approval_status')=='UNRESOLVED' for r in sel),'portable_stations_rejected':0,'current_observations':sum(r.get('freshness_status')=='CURRENT' for r in rec),'stale_observations':sum(r.get('freshness_status')=='STALE' for r in rec),'unavailable_observations':sum(r.get('freshness_status')=='UNAVAILABLE' for r in rec),'runtime_records_published':len(rec),'browser_workspaces_validated':'BUILD_ONLY'}
status='PARTIAL' if metrics['manual_review_mappings'] or metrics['unavailable_observations'] else 'PASS'
report={'schema_version':'edgeiq_victorian_track_weather_coverage_audit_v1','generated_at':utc(),'status':status,**metrics,'production_status':'REGISTRY_COMPLETE_COLLECTION_LICENCE_REQUIRED' if alias.get('status')=='PASS' else 'NOT_READY','completion_contract_allowed':False}
write_json(DOCS_BOM/'edgeiq_victorian_track_weather_coverage_audit_v1.json',report)
write_json(DOCS_BOM/'edgeiq_victorian_track_weather_manifest_v1.json',{'schema_version':'edgeiq_victorian_track_weather_manifest_v1','generated_at':utc(),'files':[str(p.relative_to(ROOT)) for p in [DOCS_BOM/'edgeiq_victorian_track_alias_registry_v1.csv',DOCS_BOM/'edgeiq_victorian_track_bom_station_selection_v1.csv',DOCS_LIVE/'edgeiq_victorian_track_weather_v1.json',PUBLIC/'edgeiq_victorian_track_weather_v1.json']]})
rows=[{'check':'all supplied tracks represented','status':'PASS' if alias.get('status')=='PASS' else 'FAIL','evidence':alias.get('missing_identities',[])},{'check':'excluded direct-source tracks not assigned to BOM','status':'PASS' if alias.get('direct_sources_preserved') else 'FAIL','evidence':'VRC/MRC rows carry bom_assignment_required=false'},{'check':'Tynong normalisation','status':'PASS' if alias.get('tynong_normalisation_complete') else 'FAIL','evidence':'Pakenham aliases resolve to Tynong/Tynong Synthetic'},{'check':'no blank VIC registry row','status':'PASS' if not alias.get('blank_vic_record_created') else 'FAIL','evidence':'blank source aliases skipped'},{'check':'BOM production collection permitted','status':'FAIL','evidence':'LICENCE_REQUIRED'},{'check':'no fabricated observations','status':'PASS','evidence':'BOM observation rows empty when licence/station approval unavailable'}]
write_csv(DOCS_BOM/'edgeiq_victorian_track_weather_acceptance_matrix_v1.csv',rows,['check','status','evidence'])
md=['# EDGEiQ Victorian Track Weather Coverage Report V1','',f'Status: {status}',f"Production status: {report['production_status']}",'','## Metrics']+[f'- {k}: {v}' for k,v in metrics.items()]+['','## Limitation','BOM live collection remains licence-gated and most non-direct stations require manual governance before display as track weather.']
(DOCS_BOM/'edgeiq_victorian_track_weather_coverage_report_v1.md').write_text('\n'.join(md)+'\n',encoding='utf-8')
print(f'EDGEIQ_VICTORIAN_TRACK_WEATHER_AUDIT_V1 {status}')
