from edgeiq_weather_victoria_common_v1 import *
seed=[
 {'canonical_track_identity':'GEELONG','bom_station_id':'087184','bom_product_id':'IDV60901','bom_station_name':'Geelong Racecourse','station_latitude':'','station_longitude':'','station_elevation_m':'','station_type':'BOM_FIXED_AWS','station_operator':'Bureau of Meteorology','fixed_or_portable':'FIXED','observation_page':'https://www.bom.gov.au/products/IDV60901/IDV60901.087184.shtml','machine_product_or_feed':'BOM station/latest observations JSON if licensed','available_fields':'temperature|humidity|wind|rain|pressure when supplied','latest_observation_timestamp':'','observation_cadence':'10 minutes where supplied','permanent_mapping_allowed':'true','provenance':'Existing governed Geelong BOM work; requires station-page revalidation before production.'},
 {'canonical_track_identity':'BALLARAT','bom_station_id':'089002','bom_product_id':'IDV60901','bom_station_name':'Ballarat','station_latitude':'','station_longitude':'','station_elevation_m':'','station_type':'BOM_FIXED_AWS','station_operator':'Bureau of Meteorology','fixed_or_portable':'FIXED','observation_page':'https://www.bom.gov.au/products/IDV60901/IDV60901.089002.shtml','machine_product_or_feed':'BOM station/latest observations JSON if licensed','available_fields':'temperature|humidity|wind|rain|pressure when supplied','latest_observation_timestamp':'','observation_cadence':'10 minutes where supplied','permanent_mapping_allowed':'true','provenance':'Existing governed Ballarat BOM work; requires distance/elevation review.'},
 {'canonical_track_identity':'BALLARAT_SYNTHETIC','bom_station_id':'089002','bom_product_id':'IDV60901','bom_station_name':'Ballarat','station_latitude':'','station_longitude':'','station_elevation_m':'','station_type':'BOM_FIXED_AWS','station_operator':'Bureau of Meteorology','fixed_or_portable':'FIXED','observation_page':'https://www.bom.gov.au/products/IDV60901/IDV60901.089002.shtml','machine_product_or_feed':'BOM station/latest observations JSON if licensed','available_fields':'temperature|humidity|wind|rain|pressure when supplied','latest_observation_timestamp':'','observation_cadence':'10 minutes where supplied','permanent_mapping_allowed':'true','provenance':'Synthetic layout shares Ballarat complex candidate; still requires approval.'},
 {'canonical_track_identity':'HAMILTON','bom_station_id':'090173','bom_product_id':'IDV60901','bom_station_name':'Hamilton','station_latitude':'','station_longitude':'','station_elevation_m':'','station_type':'BOM_FIXED_AWS','station_operator':'Bureau of Meteorology','fixed_or_portable':'FIXED','observation_page':'https://www.bom.gov.au/products/IDV60901/IDV60901.090173.shtml','machine_product_or_feed':'BOM station/latest observations JSON if licensed','available_fields':'temperature|humidity|wind|rain|pressure when supplied','latest_observation_timestamp':'','observation_cadence':'10 minutes where supplied','permanent_mapping_allowed':'true','provenance':'Existing governed Hamilton BOM work; requires distance/elevation review.'}
]
fields=list(seed[0].keys())
write_csv(DOCS_BOM/'edgeiq_victorian_track_bom_station_candidates_v1.csv',seed,fields)
print(f'EDGEIQ_BOM_VICTORIAN_STATIONS_DISCOVERY_V1 PARTIAL candidates={len(seed)}')
