from pathlib import Path

path = Path('src/components/RaceIntelligenceScreen.tsx')
text = path.read_text(encoding='utf-8')
repls = []
repls.append(('  raceShapeFallback: "/data/edgeiq_race_shape_fallback_engine_v1.csv",\n', '  raceShapeFallback: "/data/edgeiq_race_shape_fallback_engine_v1.csv",\n  mapEnrichment: "/data/edgeiq_map_enrichment_feed_v1.csv",\n'))
repls.append(('  commandEnrichment?: Row;\n', '  commandEnrichment?: Row;\n  mapEnrichment?: Row;\n'))
repls.append(('  const [raceShapeFallbackRows, setRaceShapeFallbackRows] = useState<Row[]>([]);\n', '  const [raceShapeFallbackRows, setRaceShapeFallbackRows] = useState<Row[]>([]);\n  const [mapEnrichmentRows, setMapEnrichmentRows] = useState<Row[]>([]);\n'))
repls.append(('const [runner, runnerIntel, v8, bet, rel, cards, briefing, marketIntel, verdict, trackIntel, horseDrawer, runnerDnaDrawer, explainability, connection, factorScorecard, limitedData, intelligenceScore, customerIntelligence, intelligenceSummary, raceDayIntelligence, runnerProfile, formIntelligence, runnerForm, runnerFormHistory, historyMaster, historyDetail, horseCareer, horseArchetype, horseTrajectory, horseProjection, campaignIntelligence, hiddenGem, raceShapeFallback, chaosIndex, opportunityScore, commandEnrichment] = await Promise.all([', 'const [runner, runnerIntel, v8, bet, rel, cards, briefing, marketIntel, verdict, trackIntel, horseDrawer, runnerDnaDrawer, explainability, connection, factorScorecard, limitedData, intelligenceScore, customerIntelligence, intelligenceSummary, raceDayIntelligence, runnerProfile, formIntelligence, runnerForm, runnerFormHistory, historyMaster, historyDetail, horseCareer, horseArchetype, horseTrajectory, horseProjection, campaignIntelligence, hiddenGem, raceShapeFallback, mapEnrichment, chaosIndex, opportunityScore, commandEnrichment] = await Promise.all(['))
repls.append(('        loadCsv(FILES.raceShapeFallback),\n        loadCsv(FILES.chaosIndex),\n', '        loadCsv(FILES.raceShapeFallback),\n        loadCsv(FILES.mapEnrichment),\n        loadCsv(FILES.chaosIndex),\n'))
repls.append(('      setRaceShapeFallbackRows(raceShapeFallback);\n      setChaosIndexRows(chaosIndex);\n', '      setRaceShapeFallbackRows(raceShapeFallback);\n      setMapEnrichmentRows(mapEnrichment);\n      setChaosIndexRows(chaosIndex);\n'))
repls.append(('function projectedSpdValue(item: EnrichedRunner): number | null {\n  return firstNum(item.runnerIntel, ["projected_spd"]) ??\n    firstNum(item.row, ["projected_spd", "early_speed_rating"]);\n}\n', 'function projectedSpdValue(item: EnrichedRunner): number | null {\n  return firstNum(item.mapEnrichment, ["projected_speed"]) ??\n    firstNum(item.runnerIntel, ["projected_spd"]) ??\n    firstNum(item.row, ["projected_spd", "early_speed_rating"]);\n}\n'))
repls.append(('function latePowerMetricValue(item: EnrichedRunner): number | null {\n  return firstNum(item.runnerIntel, ["late_power_index", "late_power_score"]) ??\n    firstNum(item.drawer, ["late_power_index", "late_power_score"]) ??\n    firstNum(item.row, ["late_power_index", "late_power_score"]);\n}\n', 'function latePowerMetricValue(item: EnrichedRunner): number | null {\n  return firstNum(item.mapEnrichment, ["late_speed"]) ??\n    firstNum(item.runnerIntel, ["late_power_index", "late_power_score"]) ??\n    firstNum(item.drawer, ["late_power_index", "late_power_score"]) ??\n    firstNum(item.row, ["late_power_index", "late_power_score"]);\n}\n'))
repls.append(('  const raw = firstText(\n    item.row,\n    ["settling_band", "run_style", "speed_map_bucket", "early_speed_band"],\n    firstText(\n      item.runnerIntel,\n      ["settling_band", "run_style", "early_speed_band"],\n      firstText(item.drawer, ["dominant_run_style"], "")\n    )\n  )\n', '  const raw = firstText(\n    item.mapEnrichment,\n    ["settling_position", "run_style", "lane"],\n    firstText(\n      item.row,\n      ["settling_band", "run_style", "speed_map_bucket", "early_speed_band"],\n      firstText(\n        item.runnerIntel,\n        ["settling_band", "run_style", "early_speed_band"],\n        firstText(item.drawer, ["dominant_run_style"], "")\n      )\n    )\n  )\n'))
repls.append(('function paceMapXPercent(item: EnrichedRunner): number {\n  const explicit = firstNum(item.row, ["map_x_pct"]);\n', 'function paceMapXPercent(item: EnrichedRunner): number {\n  const explicit = firstNum(item.mapEnrichment, ["map_x_pct"]) ?? firstNum(item.row, ["map_x_pct"]);\n'))
repls.append(('function factorScoreValue(item: EnrichedRunner, factorName: string): number | null {\n  return firstNum(factorRowValue(item, factorName), ["factor_score"]);\n}\n', 'function factorScoreValue(item: EnrichedRunner, factorName: string): number | null {\n  if (factorName.toUpperCase() === "PACE") {\n    return firstNum(item.mapEnrichment, ["pace_fit"]) ?? firstNum(factorRowValue(item, factorName), ["factor_score"]);\n  }\n  return firstNum(factorRowValue(item, factorName), ["factor_score"]);\n}\n'))
repls.append(('function factorBandValue(item: EnrichedRunner, factorName: string): string {\n  return firstText(factorRowValue(item, factorName), ["factor_band"], "--").replace(/_/g, " ").toUpperCase();\n}\n', 'function factorBandValue(item: EnrichedRunner, factorName: string): string {\n  if (factorName.toUpperCase() === "PACE") {\n    const mapBand = firstText(item.mapEnrichment, ["pace_fit_band"], "");\n    if (mapBand) return mapBand.replace(/_/g, " ").toUpperCase();\n  }\n  return firstText(factorRowValue(item, factorName), ["factor_band"], "--").replace(/_/g, " ").toUpperCase();\n}\n'))
repls.append(('      const commandEnrichment = findCommandEnrichmentSidecar(commandEnrichmentRows, row);\n', '      const commandEnrichment = findCommandEnrichmentSidecar(commandEnrichmentRows, row);\n      const mapEnrichment = findSidecarByRaceHorse(mapEnrichmentRows, row);\n'))
repls.append(('      return { row, runnerIntel, v8, bet, rel, drawer, dna, explainability, connection, limited, intel, customerIntel, intelligenceSummary, raceDayIntelligence, runnerProfile, formIntelligence, runnerForm, runnerHistory, runnerCareer, runnerArchetype, runnerTrajectory, runnerProjection, campaign, hiddenGem, commandEnrichment, factorRows };\n', '      return { row, runnerIntel, v8, bet, rel, drawer, dna, explainability, connection, limited, intel, customerIntel, intelligenceSummary, raceDayIntelligence, runnerProfile, formIntelligence, runnerForm, runnerHistory, runnerCareer, runnerArchetype, runnerTrajectory, runnerProjection, campaign, hiddenGem, commandEnrichment, mapEnrichment, factorRows };\n'))
repls.append(('  }, [raceRows, runnerIntelRows, v8Rows, betRows, reliabilityRows, horseDrawerRows, runnerDnaDrawerRows, explainabilityRows, connectionRows, factorScorecardRows, limitedDataRows, intelligenceScoreRows, customerIntelligenceRows, intelligenceSummaryRows, runnerProfileRows, formIntelligenceRows, runnerFormRows, historyMasterByHorse, historyMasterByTrackRaceHorse, historyDetailByHorse, historyDetailByMergeKey, historyDetailByLooseMergeKey, runnerFormHistoryByHorse, horseCareerByHorse, horseArchetypeByHorse, horseTrajectoryByHorse, horseProjectionByHorse, campaignIntelligenceRows, hiddenGemRows, commandEnrichmentRows]);\n', '  }, [raceRows, runnerIntelRows, v8Rows, betRows, reliabilityRows, horseDrawerRows, runnerDnaDrawerRows, explainabilityRows, connectionRows, factorScorecardRows, limitedDataRows, intelligenceScoreRows, customerIntelligenceRows, intelligenceSummaryRows, runnerProfileRows, formIntelligenceRows, runnerFormRows, historyMasterByHorse, historyMasterByTrackRaceHorse, historyDetailByHorse, historyDetailByMergeKey, historyDetailByLooseMergeKey, runnerFormHistoryByHorse, horseCareerByHorse, horseArchetypeByHorse, horseTrajectoryByHorse, horseProjectionByHorse, campaignIntelligenceRows, hiddenGemRows, commandEnrichmentRows, mapEnrichmentRows]);\n'))
repls.append(('  const selectedProjectedSpd = selected\n    ? firstNum(selected.runnerIntel, ["projected_spd"]) ?? firstNum(selected.row, ["projected_spd"])\n    : null;\n', '  const selectedProjectedSpd = selected ? projectedSpdValue(selected) : null;\n'))
repls.append(('    const explicitY = firstNum(item.row, ["map_y_px"]);\n', '    const explicitY = firstNum(item.mapEnrichment, ["map_y_px"]) ?? firstNum(item.row, ["map_y_px"]);\n'))
repls.append(('      const explicitMap = firstNum(item.row, ["map_x_pct"]);\n', '      const explicitMap = firstNum(item.mapEnrichment, ["map_x_pct"]) ?? firstNum(item.row, ["map_x_pct"]);\n'))

for old, new in repls:
    if old not in text:
        raise SystemExit(f'Missing expected text for replacement: {old[:120]}')
    text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8')
print('MAP_TSX_FALLBACK_WIRE_APPLIED')
