from pathlib import Path
p=Path('src/components/RaceIntelligenceScreen.tsx')
checkpoint=Path('src/components/RaceIntelligenceScreen_CHECKPOINT_FORM_DEFECT_CLEANUP_V1_20260628.tsx')
text=p.read_text(encoding='utf-8')
checkpoint.write_text(text,encoding='utf-8')
start=text.index('      {intelMode === "FORM" ? (')
end=text.index('      {intelMode === "RUNNERS" ? (',start)
block=text[start:end]
# Prefer display status/quality/trend/score.
block=block.replace('const selectedFormStatus = firstText(selectedRunnerForm, ["form_truth_status", "form_v4_truth_status"], "NOT LOADED").replace(/_/g, " ").toUpperCase();', 'const selectedFormStatus = firstText(selectedRunnerForm, ["form_status_display", "form_truth_status", "form_v4_truth_status"], "UNKNOWN").replace(/_/g, " ").toUpperCase();')
block=block.replace('const selectedFormDataQuality = firstText(selectedRunnerForm, ["form_data_quality", "form_truth_status"], selectedFormStatus).replace(/_/g, " ").toUpperCase();', 'const selectedFormDataQuality = firstText(selectedRunnerForm, ["form_data_quality_display", "form_data_quality", "form_truth_status"], selectedFormStatus).replace(/_/g, " ").toUpperCase();')
block=block.replace('const selectedFormScore = selected ? (firstNum(selectedRunnerForm, ["form_peak_rating_last5", "form_avg_rating_last5", "form_last_start_rating"]) ?? projectionRatingValue(selected)) : null;', 'const selectedFormScore = selected ? (firstNum(selectedRunnerForm, ["form_score_display", "form_peak_rating_last5", "form_avg_rating_last5", "form_last_start_rating"]) ?? projectionRatingValue(selected)) : null;')
block=block.replace('const selectedTrendRaw = firstText(selectedRunnerForm, ["form_signal", "form_trend", "rating_trend", "form_cycle", "form_data_quality"], selectedIsContextOnly ? "CONTEXT ONLY" : "LIMITED FORM").replace(/_/g, " ").toUpperCase();', 'const selectedTrendRaw = firstText(selectedRunnerForm, ["form_trend_display", "form_signal", "form_trend", "rating_trend", "form_cycle", "form_data_quality_display"], selectedIsContextOnly ? "CONTEXT ONLY" : "LIMITED FORM").replace(/_/g, " ").toUpperCase();')
block=block.replace('const selectedFormScoreBand = selectedFormScore === null ? "LIMITED" : selectedFormScore >= 85 ? "ELITE" : selectedFormScore >= 75 ? "STRONG" : selectedFormScore >= 60 ? "AVERAGE" : selectedFormScore >= 45 ? "RISK" : "POOR";', 'const selectedFormScoreBand = firstText(selectedRunnerForm, ["form_score_band_display"], "") || (selectedFormScore === null ? "LIMITED" : selectedFormScore >= 85 ? "ELITE" : selectedFormScore >= 75 ? "STRONG" : selectedFormScore >= 60 ? "AVERAGE" : selectedFormScore >= 45 ? "RISK" : "POOR");')
# Improve margin helper for display-clean fallback.
block=block.replace('const marginDisplay = (finish: string, margin: string) => {\n          if (!margin) return "--";\n          const clean = margin.endsWith("L") ? margin : `${margin}L`;\n          return String(finish || "").replace(/[^0-9]/g, "") === "1" ? `Won by ${clean}` : `Beaten ${clean}`;\n        };', 'const marginDisplay = (finish: string, margin: string) => {\n          if (!margin || margin === "--") return "--";\n          if (margin.includes("Won") || margin.includes("Beaten")) return margin;\n          const numeric = Number(String(margin).replace(/[^0-9.\-]/g, ""));\n          if (!Number.isFinite(numeric)) return "--";\n          if (String(finish || "").replace(/[^0-9]/g, "") === "1") return numeric > 0 ? `Won by ${numeric.toFixed(1)}L` : "Won";\n          return numeric > 0 ? `Beaten ${numeric.toFixed(1)}L` : "--";\n        };')
# Setup profiles use display fields first.
block=block.replace('const distanceProfile = setupProfileText("Distance", distanceProfileRaw || firstText(selected.row, ["distance", "race_distance", "distance_m", "race_distance_m"], ""), firstNum(selected.row, ["distance_fit_score", "score_distance", "edgeiq_score_distance_v3", "distance_score"]), "Current trip");\n        const conditionProfile = setupProfileText("Condition", conditionProfileRaw || firstText(selected.row, ["condition", "track_condition", "official_condition", "edgeiq_condition"], ""), firstNum(selected.row, ["condition_fit_score", "score_condition", "edgeiq_score_condition_v3", "condition_score"]), "Current going");\n        const classProfile = setupProfileText("Class", classProfileRaw || firstText(selected.row, ["race_class", "class", "class_name"], ""), firstNum(selected.row, ["class_fit_score", "score_class", "edgeiq_score_class_v3", "class_score"]), "Current class");', 'const distanceProfile = firstText(selectedRunnerForm, ["distance_profile_display"], "") || setupProfileText("Distance", distanceProfileRaw || firstText(selected.row, ["distance", "race_distance", "distance_m", "race_distance_m"], ""), firstNum(selected.row, ["distance_fit_score", "score_distance", "edgeiq_score_distance_v3", "distance_score"]), "Current trip");\n        const conditionProfile = firstText(selectedRunnerForm, ["condition_profile_display"], "") || setupProfileText("Condition", conditionProfileRaw || firstText(selected.row, ["condition", "track_condition", "official_condition", "edgeiq_condition"], ""), firstNum(selected.row, ["condition_fit_score", "score_condition", "edgeiq_score_condition_v3", "condition_score"]), "Current going");\n        const classProfile = firstText(selectedRunnerForm, ["class_profile_display"], "") || setupProfileText("Class", classProfileRaw || firstText(selected.row, ["race_class", "class", "class_name"], ""), firstNum(selected.row, ["class_fit_score", "score_class", "edgeiq_score_class_v3", "class_score"]), "Current class");')
# Last five use display fields.
block=block.replace('const going = firstText(selectedRunnerForm, [`${prefix}condition`], "");', 'const going = firstText(selectedRunnerForm, [`${prefix}condition_display`, `${prefix}condition`], "UNKNOWN");')
block=block.replace('const dist = firstText(selectedRunnerForm, [`${prefix}distance`], "");', 'const dist = firstText(selectedRunnerForm, [`${prefix}distance_display`, `${prefix}distance`], "--");')
block=block.replace('const cls = firstText(selectedRunnerForm, [`${prefix}class`], "");', 'const cls = firstText(selectedRunnerForm, [`${prefix}class_display`, `${prefix}class`], "UNKNOWN");')
block=block.replace('const pos = firstText(selectedRunnerForm, [`${prefix}finish`, `${prefix}finishing_position`], "");', 'const pos = firstText(selectedRunnerForm, [`${prefix}position_display`, `${prefix}finish`, `${prefix}finishing_position`], "--");')
block=block.replace('const margin = firstText(selectedRunnerForm, [`${prefix}margin`, `${prefix}beaten_margin`], "");', 'const margin = firstText(selectedRunnerForm, [`${prefix}margin_display`, `${prefix}margin`, `${prefix}beaten_margin`], "--");')
block=block.replace('const sp = firstText(selectedRunnerForm, [`${prefix}sp`, `${prefix}SP`], "");', 'const sp = firstText(selectedRunnerForm, [`${prefix}sp_display`, `${prefix}sp`, `${prefix}SP`], "--");')
block=block.replace('const rating = firstNum(selectedRunnerForm, [`${prefix}rating`]);', 'const ratingText = firstText(selectedRunnerForm, [`${prefix}rating_display`, `${prefix}rating`], "--");\n          const rating = firstNum({ ratingText }, ["ratingText"]);')
block=block.replace('const rawSource = firstText(selectedRunnerForm, [`${prefix}source`, `${prefix}reason`, `${prefix}performance_label`], "");\n          const source = customerSourceLabel(rawSource);', 'const source = firstText(selectedRunnerForm, [`${prefix}comment_display`], "") || customerSourceLabel(firstText(selectedRunnerForm, [`${prefix}source`, `${prefix}reason`, `${prefix}performance_label`], ""));')
# Left runner status one clean line only, no trend on second line.
block=block.replace('const itemQuality = firstText(itemForm, ["form_data_quality", "form_truth_status"], "").replace(/_/g, " ").toUpperCase();\n                      const itemScore = firstNum(itemForm, ["form_peak_rating_last5", "form_avg_rating_last5", "form_last_start_rating"]) ?? projectionRatingValue(item);\n                      const itemTrend = firstText(itemForm, ["form_signal", "form_trend", "rating_trend", "form_data_quality"], itemQuality || "FORM").replace(/_/g, " ").toUpperCase();', 'const itemQuality = firstText(itemForm, ["form_status_display", "form_data_quality_display", "form_data_quality", "form_truth_status"], "PARTIAL EVIDENCE").replace(/_/g, " ").toUpperCase();\n                      const itemScore = firstNum(itemForm, ["form_score_display", "form_peak_rating_last5", "form_avg_rating_last5", "form_last_start_rating"]) ?? projectionRatingValue(item);\n                      const itemTrend = firstText(itemForm, ["form_trend_display"], itemQuality).replace(/_/g, " ").toUpperCase();')
block=block.replace('<span style={{ display: "flex", gap: 6, alignItems: "center", minWidth: 0 }}>\n                              <em style={{ color: "#94a3b8", fontSize: 9.5, fontStyle: "normal", fontWeight: 850, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{itemQuality || "Partial Evidence"}</em>\n                              <em style={{ color: itemTrend.includes("IMPROV") || itemTrend.includes("PEAK") ? "#34d399" : itemTrend.includes("REGRESS") ? "#f87171" : itemTrend.includes("CONTEXT") ? "#94a3b8" : "#f5c451", fontSize: 9.5, fontStyle: "normal", fontWeight: 950, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{itemTrend}</em>\n                            </span>', '<span style={{ color: itemQuality.includes("FULL") || itemQuality.includes("OK") ? "#34d399" : itemQuality.includes("PARTIAL") ? "#7dd3fc" : itemQuality.includes("CONTEXT") ? "#94a3b8" : "#f5c451", fontSize: 9.5, fontWeight: 950, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{itemQuality || "PARTIAL EVIDENCE"}</span>')
# Header hide missing weight age and line-break details.
old='''                        <div style={{ color: "#cbd5e1", fontSize: 12, fontWeight: 850, lineHeight: 1.45 }}>
                          No {saddle(selected.row) === 999 ? "--" : saddle(selected.row)} | Barrier {firstText(selected.row, ["barrier", "barrier_no", "draw"], "--")} | Trainer {firstText(selected.row, ["trainer", "trainer_name"], "not loaded")} | Jockey {firstText(selected.row, ["jockey", "jockey_name"], "not loaded")} | {firstText(selected.row, ["weight", "weight_carried", "allocated_weight"], "weight --")} | {firstText(selected.row, ["age_sex", "age", "sex"], "age/sex --")}
                        </div>'''
new='''                        <div style={{ color: "#cbd5e1", fontSize: 12, fontWeight: 850, lineHeight: 1.55, display: "grid", gap: 2 }}>
                          <span>No {saddle(selected.row) === 999 ? "--" : saddle(selected.row)} | Barrier {firstText(selected.row, ["barrier", "barrier_no", "draw"], "--")}</span>
                          <span>Trainer: {firstText(selected.row, ["trainer", "trainer_name"], "not loaded")}</span>
                          <span>Jockey: {firstText(selected.row, ["jockey", "jockey_name"], "not loaded")}</span>
                          {firstText(selected.row, ["weight", "weight_carried", "allocated_weight"], "") ? <span>Weight: {firstText(selected.row, ["weight", "weight_carried", "allocated_weight"], "")}</span> : null}
                          {firstText(selected.row, ["age_sex", "age", "sex"], "") ? <span>Age/Sex: {firstText(selected.row, ["age_sex", "age", "sex"], "")}</span> : null}
                        </div>'''
block=block.replace(old,new)
# Form Status rows use displays and evidence.
block=block.replace('{ title: "Form Status", rows: [["Status", selectedFormStatus], ["Signal", firstText(selectedRunnerForm, ["form_signal"], "--")], ["Trend", selectedTrendRead], ["Quality", selectedFormDataQuality]] },', '{ title: "Form Status", rows: [["Status", selectedFormStatus], ["Trend", selectedTrendRead], ["Data", selectedFormDataQuality], ["Evidence", firstText(selectedRunnerForm, ["form_evidence_display"], "LOW")]] },')
# Today setup no not loaded.
block=block.replace('"not loaded"', '"--"')
block=block.replace('>{run.cls || "--"}</span>', '>{run.cls || "UNKNOWN"}</span>')
block=block.replace('>{run.going || "--"}</span>', '>{run.going || "UNKNOWN"}</span>')
# Verdict line breaks.
block=block.replace('<p style={{ color: "#dbe7fb", fontSize: 12, lineHeight: 1.5, margin: "8px 0 0", fontWeight: 850 }}>{selectedFormVerdict}{missingDetail ? ` Some setup fields are not loaded from source: ${missingDetail}.` : ""}</p>', '<p style={{ color: "#dbe7fb", fontSize: 12, lineHeight: 1.55, margin: "8px 0 0", fontWeight: 850, whiteSpace: "pre-line" }}>{selectedFormVerdict.split(". ").join(".\\n\\n")}{missingDetail ? `\\n\\nSome setup fields are not loaded from source: ${missingDetail}.` : ""}</p>')
text=text[:start]+block+text[end:]
p.write_text(text,encoding='utf-8')
print('FORM defect cleanup TSX V1 applied')
print(f'checkpoint={checkpoint}')
