from pathlib import Path
p=Path('src/components/RaceIntelligenceScreen.tsx')
text=p.read_text(encoding='utf-8')
repls=[]
repls.append(('  runnerProfile: "/data/edgeiq_runner_profile_engine_current.csv",\n','  runnerProfile: "/data/edgeiq_runners_enrichment_feed_v1.csv",\n'))
repls.append(('function confidenceScoreValue(item: EnrichedRunner): number | null {\n  return firstNum(item.runnerIntel, ["confidence_score"]) ??\n    firstNum(item.drawer, ["confidence_score"]) ??\n    firstNum(item.intel, ["confidence_score", "intelligence_reliability_component_v1"]) ??\n    firstNum(item.row, ["confidence_score"]);\n}\n','function confidenceScoreValue(item: EnrichedRunner): number | null {\n  return firstNum(item.runnerProfile, ["confidence_score"]) ??\n    firstNum(item.runnerIntel, ["confidence_score"]) ??\n    firstNum(item.drawer, ["confidence_score"]) ??\n    firstNum(item.intel, ["confidence_score", "intelligence_reliability_component_v1"]) ??\n    firstNum(item.row, ["confidence_score"]);\n}\n'))
repls.append(('function dnaScoreValue(item: EnrichedRunner): number | null {\n  return firstNum(item.dna, ["dna_v6_2_score", "runner_dna_v6_1_score", "dna_score"]) ??\n    firstNum(item.row, ["dna_v6_2_score", "runner_dna_v6_1_score", "dna_score"]);\n}\n','function dnaScoreValue(item: EnrichedRunner): number | null {\n  return firstNum(item.dna, ["dna_v6_2_score", "runner_dna_v6_1_score", "dna_score"]) ??\n    firstNum(item.runnerProfile, ["dna_v6_2_score", "dna_score"]) ??\n    firstNum(item.row, ["dna_v6_2_score", "runner_dna_v6_1_score", "dna_score"]);\n}\n'))
repls.append(('function projectionRatingValue(item: EnrichedRunner): number | null {\n  return firstNum(item.row, ["projected_rating_V6_1_RESEARCH", "projected_rating_v5_2"]);\n}\n','function projectionRatingValue(item: EnrichedRunner): number | null {\n  return firstNum(item.row, ["projected_rating_V6_1_RESEARCH", "projected_rating_v5_2"]) ??\n    firstNum(item.runnerProfile, ["projected_rating", "rating_ladder_score"]);\n}\n'))
repls.append(('  const selectedDnaScore = selected ? firstText(selected.dna, ["dna_v6_2_score", "runner_dna_v6_1_score"], "--") : "--";\n','  const selectedDnaScore = selected ? firstText(selected.dna, ["dna_v6_2_score", "runner_dna_v6_1_score"], firstText(selectedProfile, ["dna_v6_2_score", "dna_score"], "--")) : "--";\n'))
repls.append(('  const selectedDnaBand = selected ? firstText(selected.dna, ["dna_v6_2_band", "runner_dna_v6_1_band"], "--").replace(/_/g, " ").toUpperCase() : "--";\n','  const selectedDnaBand = selected ? firstText(selected.dna, ["dna_v6_2_band", "runner_dna_v6_1_band"], firstText(selectedProfile, ["dna_v6_2_band", "dna_band"], "--")).replace(/_/g, " ").toUpperCase() : "--";\n'))
repls.append(('  const selectedStrongestFactor = selected ? firstText(selected.dna, ["strongest_factor_v6_2", "strongest_factor_v6_1"], "--").replace(/_/g, " ").toUpperCase() : "--";\n','  const selectedStrongestFactor = selected ? firstText(selected.dna, ["strongest_factor_v6_2", "strongest_factor_v6_1"], firstText(selectedProfile, ["positive_1_factor"], "--")).replace(/_/g, " ").toUpperCase() : "--";\n'))
repls.append(('  const selectedWeakestFactor = selected ? firstText(selected.dna, ["weakest_factor_v6_2", "weakest_factor_v6_1"], "--").replace(/_/g, " ").toUpperCase() : "--";\n','  const selectedWeakestFactor = selected ? firstText(selected.dna, ["weakest_factor_v6_2", "weakest_factor_v6_1"], firstText(selectedProfile, ["negative_1_factor"], "--")).replace(/_/g, " ").toUpperCase() : "--";\n'))
for i in [1,2,3]:
    repls.append((f'  const selectedPositive{i}Factor = selected ? firstText(selected.dna, ["positive_{i}_factor"], "--").replace(/_/g, " ").toUpperCase() : "--";\n', f'  const selectedPositive{i}Factor = selected ? firstText(selected.dna, ["positive_{i}_factor"], firstText(selectedProfile, ["positive_{i}_factor"], "--")).replace(/_/g, " ").toUpperCase() : "--";\n'))
    repls.append((f'  const selectedPositive{i}Impact = selected ? firstText(selected.dna, ["positive_{i}_impact"], "--") : "--";\n', f'  const selectedPositive{i}Impact = selected ? firstText(selected.dna, ["positive_{i}_impact"], firstText(selectedProfile, ["positive_{i}_impact"], "--")) : "--";\n'))
    repls.append((f'  const selectedNegative{i}Factor = selected ? firstText(selected.dna, ["negative_{i}_factor"], "--").replace(/_/g, " ").toUpperCase() : "--";\n', f'  const selectedNegative{i}Factor = selected ? firstText(selected.dna, ["negative_{i}_factor"], firstText(selectedProfile, ["negative_{i}_factor"], "--")).replace(/_/g, " ").toUpperCase() : "--";\n'))
    repls.append((f'  const selectedNegative{i}Impact = selected ? firstText(selected.dna, ["negative_{i}_impact"], "--") : "--";\n', f'  const selectedNegative{i}Impact = selected ? firstText(selected.dna, ["negative_{i}_impact"], firstText(selectedProfile, ["negative_{i}_impact"], "--")) : "--";\n'))
for old,new in repls:
    if old not in text:
        raise SystemExit('missing replacement: '+old[:120])
    text=text.replace(old,new,1)
p.write_text(text,encoding='utf-8')
print('RUNNERS_TSX_FALLBACK_WIRE_APPLIED')
