from pathlib import Path
p=Path('scripts/build_edgeiq_performance_recovery_current_lineage_v1.py')
s=p.read_text(encoding='utf-8')
old="rec={'raceDate':rdace,'meeting':meet,'raceNumber':rn,'runnerNumber':it(r.get('runnerNumber')),'runnerName':horse,'normalisedRunnerName':hk,'epi':{'value':cv,'display':fmt(cv,1) if cv is not None else '', 'source':'edgeiq_epi_performance_fact_v1.csv:latest_prior_fullForm_match' if cv is not None else None,'version':'EPI_LINEAGE_RECOVERY_V1','asAt':TS,'status':status,'rankInRace':None,'activeFieldSize':None,'fieldHigh':None,'fieldAverage':None,'differenceFromFieldAverage':None,'recentChange':None,'trend':trend,'unavailableReason':un},'eri':{'value':ce,'display':fmt(ce,1) if ce is not None else '', 'source':'edgeiq_epi_race_strength_fact_v1.csv:latest_prior_run_race' if ce is not None else None,'version':'ERI_LINEAGE_RECOVERY_V1','asAt':TS,'status':'ERI_PRIOR_CONTEXT_AVAILABLE' if ce is not None else 'ERI_UNAVAILABLE','unavailableReason':un},'observationsUsed':len(ms),'latestPerformanceId':last['pid'] if ms else '','joinMethod':last['method'] if ms else ''}"
new="rec={'raceDate':rdace,'meeting':meet,'raceNumber':rn,'runnerNumber':it(r.get('runnerNumber')),'runnerName':horse,'normalisedRunnerName':hk,'value':cv,'display':fmt(cv,1) if cv is not None else '', 'source':'edgeiq_epi_performance_fact_v1.csv:latest_prior_fullForm_match' if cv is not None else None,'version':'EPI_LINEAGE_RECOVERY_V1','asAt':TS,'status':status,'rankInRace':None,'activeFieldSize':None,'fieldHigh':None,'fieldAverage':None,'differenceFromFieldAverage':None,'recentChange':None,'trend':trend,'unavailableReason':un,'eriValue':ce,'eriDisplay':fmt(ce,1) if ce is not None else '', 'eriSource':'edgeiq_epi_race_strength_fact_v1.csv:latest_prior_run_race' if ce is not None else None,'eriStatus':'ERI_PRIOR_CONTEXT_AVAILABLE' if ce is not None else 'ERI_UNAVAILABLE','epi':{'value':cv,'display':fmt(cv,1) if cv is not None else '', 'source':'edgeiq_epi_performance_fact_v1.csv:latest_prior_fullForm_match' if cv is not None else None,'version':'EPI_LINEAGE_RECOVERY_V1','asAt':TS,'status':status,'rankInRace':None,'activeFieldSize':None,'fieldHigh':None,'fieldAverage':None,'differenceFromFieldAverage':None,'recentChange':None,'trend':trend,'unavailableReason':un},'eri':{'value':ce,'display':fmt(ce,1) if ce is not None else '', 'source':'edgeiq_epi_race_strength_fact_v1.csv:latest_prior_run_race' if ce is not None else None,'version':'ERI_LINEAGE_RECOVERY_V1','asAt':TS,'status':'ERI_PRIOR_CONTEXT_AVAILABLE' if ce is not None else 'ERI_UNAVAILABLE','unavailableReason':un},'observationsUsed':len(ms),'latestPerformanceId':last['pid'] if ms else '','joinMethod':last['method'] if ms else ''}"
if old not in s:
    raise SystemExit('target rec block not found')
p.write_text(s.replace(old,new),encoding='utf-8')
print('PATCHED current epi top-level mirrors')
