import { useEffect, useMemo, useState } from "react";
import type { CSSProperties } from "react";
import type { ThreeDayRunner } from "../services/threeDayCatalog";
import { buildMapViewModel, loadMapTerminalFeed, type BETA009Row } from "../services/mapFeed";

type RaceFieldRunner = ThreeDayRunner & Record<string, unknown>;
type Props={raceBook:Record<string,unknown>;field?:RaceFieldRunner[];selectedRunner?:RaceFieldRunner|null;clean:(value:unknown)=>string;market:(value:unknown)=>string;onOpenRunner?:(runner:RaceFieldRunner)=>void;mode?:string};
function txt(v:unknown){const s=String(v??"").trim();return s==="-"?"":s}
function name(row:BETA009Row){return txt(row.horse)||"Runner"} function no(row:BETA009Row){return txt(row.no)}
function lane(row:BETA009Row){const speed=Number(txt(row.early_speed));if(Number.isFinite(speed)&&speed>0)return Math.max(10,Math.min(84,88-speed*.7));const s=txt(row.run_style).toUpperCase();if(s.includes("LEAD"))return 16;if(/PACE|FORWARD/.test(s))return 31;if(s.includes("MID"))return 52;if(/BACK|REAR/.test(s))return 73;return 86}
function evidence(row:BETA009Row){return Boolean(row.run_style||row.early_speed||row.projected_position)}
function runnerName(r:any){return txt(r?.official?.runner||r?.runner||r?.horse||r?.name).toUpperCase()}
export function MapWorkspace({raceBook,field=[],selectedRunner,onOpenRunner}:Props){
 const [feed,setFeed]=useState<Awaited<ReturnType<typeof loadMapTerminalFeed>>>([]); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{let stop=false;loadMapTerminalFeed().then(x=>{if(!stop){setFeed(x);setError(null)}}).catch(e=>{if(!stop){setFeed([]);setError(e instanceof Error?e.message:"Speed map feed unavailable")}});return()=>{stop=true}},[]);
 const official=(raceBook.official??{}) as any; const race={raceKey:txt(official.raceKey)||`${txt(official.meeting)}|R${txt(official.raceNumber)}`,raceNumber:Number(txt(official.raceNumber)||0),raceName:txt(official.raceName)||`Race ${txt(official.raceNumber)}`,distance:txt(official.distance)||null,raceClass:txt(official.raceClass)||null,raceTime:txt(official.raceTime)||null,trackCondition:txt(official.trackCondition)||null,rail:txt(official.rail)||null,runners:field,source:(raceBook.source??{}) as any};
 const vm=useMemo(()=>buildMapViewModel(race,feed,null),[feed,race.raceKey]); const rows=vm.rows; const mapped=rows.filter(evidence); const leaders=mapped.filter(r=>/LEAD/i.test(txt(r.run_style))); const pace=mapped.filter(r=>/PACE|FORWARD/i.test(txt(r.run_style))); const selected=selectedRunner?rows.find(r=>name(r).toUpperCase()===runnerName(selectedRunner)):null;
 if(error)return <section className="eiq-map-v3"><div className="eiq-module-empty">{error}</div></section>;
 return <section className="eiq-map-v3" aria-label="Speed map workspace">
  <div className="eiq-map-v3__stats"><article><span>MAP STATUS</span><strong>{mapped.length?"CURRENT":"AWAITING"}</strong></article><article><span>POSITION READS</span><strong>{mapped.length}/{rows.length}</strong></article><article><span>LEAD PRESSURE</span><strong>{leaders.length>=2?"HIGH":leaders.length===1?"CONTROLLED":"UNKNOWN"}</strong></article><article><span>FORWARD RUNNERS</span><strong>{leaders.length+pace.length}</strong></article></div>
  <div className="eiq-map-v3__layout"><section className="eiq-map-v3__canvas"><header><div><strong>PROJECTED SETTLING MAP</strong><span>Start / barriers → expected settling position → finish</span></div><b>RACING ←</b></header><div className="eiq-map-v3__track"><div className="eiq-map-v3__zones"><span>LEAD</span><span>ON PACE</span><span>MIDFIELD</span><span>BACK</span></div>{rows.map((row,index)=>{const source=(row as any).runner as RaceFieldRunner|undefined;const style={"--map-x":`${lane(row)}%`,"--map-y":`${8+(index%12)*7.4}%`} as CSSProperties;return <button key={`${no(row)}-${name(row)}`} style={style} className={`eiq-map-v3__runner ${evidence(row)?"":"is-pending"} ${selected===row?"is-selected":""}`} onClick={()=>source&&onOpenRunner?.(source)} disabled={!source}><b>{no(row)||index+1}</b><span>{name(row)}</span><small>{txt(row.early_speed)||txt(row.run_style)||"No speed"}</small></button>})}</div></section>
  <aside className="eiq-map-v3__side"><section><header>RACE SHAPE</header><dl><div><dt>Likely leaders</dt><dd>{leaders.map(name).join(", ")||"Awaiting"}</dd></div><div><dt>On pace</dt><dd>{pace.map(name).join(", ")||"Awaiting"}</dd></div><div><dt>Pressure</dt><dd>{leaders.length>=2?"Contested lead":leaders.length===1?"Potential control":"Insufficient evidence"}</dd></div></dl></section><section><header>MAP INTERPRETATION</header><p>The map is a tactical decision surface. Use it with barrier, early speed and race pressure rather than treating settling position as a fixed prediction.</p></section></aside></div>
  <section className="eiq-map-v3__table"><header><strong>FIELD MAP DATA</strong><span>Barrier and speed evidence</span></header><table><thead><tr><th>NO</th><th>RUNNER</th><th>BAR</th><th>EFFECTIVE</th><th>RUN STYLE</th><th>EARLY SPEED</th><th>PROJECTED</th><th>EVIDENCE</th></tr></thead><tbody>{rows.map(row=><tr key={`table-${no(row)}-${name(row)}`}><td>{no(row)}</td><td><strong>{name(row)}</strong></td><td>{txt(row.barrier)||"-"}</td><td>{txt(row.effective_barrier)||"-"}</td><td>{txt(row.run_style)||"-"}</td><td>{txt(row.early_speed)||"-"}</td><td>{txt(row.projected_position)||"-"}</td><td>{evidence(row)?"Current":"Pending"}</td></tr>)}</tbody></table></section>
 </section>
}
