import { useEffect, useMemo, useState } from "react";
import type { ThreeDayMeeting, ThreeDayRace } from "../services/threeDayCatalog";
import { canonicalRailDisplay, canonicalTrackDisplayName, canonicalTrackRatingDisplay, canonicalWeatherDisplay, cleanProductText } from "../../design-system/presentation";
import { loadMeetingDetail, loadMeetingsWorkspaceViewModel, type MeetingSummaryViewModel, type MeetingsDayKey, type MeetingsWorkspaceViewModel } from "../services/meetingsFeed";
import { loadRaceDetail } from "../services/raceDetailFeed";

type MeetingsWorkspaceProps = { selectedDayKey: MeetingsDayKey; selectedMeetingKey: string | null; clean: (value: any) => string; onDayChange: (day: MeetingsDayKey) => void; onSelectMeeting: (meeting: ThreeDayMeeting | null) => void; onOpenMeeting: (meeting: ThreeDayMeeting) => void; onOpenRace: (meeting: ThreeDayMeeting, race: ThreeDayRace, index: number) => void; };
type Jurisdiction = "VIC" | "WA" | "HK" | "OTHER";
const display = (value: unknown, fallback = "—") => cleanProductText(value, fallback);
const JURISDICTIONS: Record<Jurisdiction, { name: string; authority: string; code: string }> = { VIC: { name: "Victoria", authority: "Racing Victoria", code: "RV" }, WA: { name: "Western Australia", authority: "Racing WA", code: "RWA" }, HK: { name: "Hong Kong", authority: "Hong Kong Jockey Club", code: "HKJC" }, OTHER: { name: "Other", authority: "Racing Authority", code: "PRA" } };
function jurisdictionOf(meeting: MeetingSummaryViewModel): Jurisdiction { const state = display(meeting.state, "").toUpperCase(); const name = canonicalTrackDisplayName(meeting.meeting).toUpperCase(); if (state === "VIC" || state.includes("VICTORIA")) return "VIC"; if (state === "WA" || state.includes("WESTERN AUSTRALIA")) return "WA"; if (state === "HK" || state.includes("HONG KONG") || /SHA TIN|HAPPY VALLEY/.test(name)) return "HK"; return "OTHER"; }
function shortDate(value: string) { const [year, month, day] = value.split("-").map(Number); if (!year || !month || !day) return value; return new Intl.DateTimeFormat("en-AU", { weekday: "short", day: "numeric", month: "short", timeZone: "Australia/Melbourne" }).format(new Date(Date.UTC(year, month - 1, day))); }
function tabTitle(index: number) { return index === 0 ? "Today" : index === 1 ? "Tomorrow" : "Day +2"; }

export function MeetingsWorkspace({ selectedDayKey, selectedMeetingKey, onDayChange, onSelectMeeting, onOpenMeeting, onOpenRace }: MeetingsWorkspaceProps) {
  const [model, setModel] = useState<MeetingsWorkspaceViewModel | null>(null); const [loading, setLoading] = useState(true); const [detailLoading, setDetailLoading] = useState(false); const [loadError, setLoadError] = useState(""); const [search, setSearch] = useState(""); const [jurisdictionFilter, setJurisdictionFilter] = useState<"ALL" | Jurisdiction>("ALL");
  useEffect(() => { let active = true; loadMeetingsWorkspaceViewModel().then((next) => { if (active) { setModel(next); setLoading(false); setLoadError(""); } }).catch((error) => { if (active) { setModel(null); setLoading(false); setLoadError(error instanceof Error ? error.message : "Meetings feed unavailable"); } }); return () => { active = false; }; }, []);
  const activeDay = model?.days.find((day) => day.key === selectedDayKey) ?? model?.days[0] ?? null;
  const meetings = useMemo(() => { const q = search.trim().toLowerCase(); return (activeDay?.meetings ?? []).filter((meeting) => { const jurisdiction = jurisdictionOf(meeting); const name = canonicalTrackDisplayName(meeting.meeting).toLowerCase(); return (!q || name.includes(q)) && (jurisdictionFilter === "ALL" || jurisdiction === jurisdictionFilter); }); }, [activeDay, search, jurisdictionFilter]);
  const grouped = useMemo(() => (["VIC", "WA", "HK", "OTHER"] as Jurisdiction[]).map((key) => ({ key, meetings: meetings.filter((meeting) => jurisdictionOf(meeting) === key) })).filter((group) => group.meetings.length > 0), [meetings]);
  async function openMeeting(meeting: MeetingSummaryViewModel) { setDetailLoading(true); setLoadError(""); try { const detail = await loadMeetingDetail(meeting.rawMeeting.date, meeting.meetingKey); onSelectMeeting(detail); onOpenMeeting(detail); } catch (error) { setLoadError(error instanceof Error ? error.message : "Meeting detail unavailable"); } finally { setDetailLoading(false); } }
  async function openFirstRace(meeting: MeetingSummaryViewModel) { const race = meeting.raceSummaries[0]; if (!race) return void openMeeting(meeting); setDetailLoading(true); setLoadError(""); try { const [meetingDetail, raceDetail] = await Promise.all([loadMeetingDetail(meeting.rawMeeting.date, meeting.meetingKey), loadRaceDetail(meeting.rawMeeting.date, meeting.meetingKey, race.raceKey)]); const merged: ThreeDayMeeting = { ...meetingDetail, races: meetingDetail.races.map((item) => item.raceKey === race.raceKey ? raceDetail : item) }; onSelectMeeting(merged); onOpenRace(merged, raceDetail, 0); } catch (error) { setLoadError(error instanceof Error ? error.message : "Race detail unavailable"); } finally { setDetailLoading(false); } }
  if (loading) return <section className="eiq-meetings-locked"><div className="eiq-meetings-locked__empty">Loading meetings…</div></section>;
  return <section className="eiq-meetings-locked" aria-label="Meetings" data-edgeiq-workspace-key="MEETINGS">
    <header className="eiq-meetings-locked__header"><div><h1>Meetings</h1><p>Select a meeting to open its race programme.</p>{loadError ? <p role="alert">{loadError}</p> : null}</div></header>
    <div className="eiq-meetings-locked__days" aria-label="Meeting days">{(model?.days ?? []).slice(0, 3).map((day, index) => <button key={day.key} type="button" className={day.key === activeDay?.key ? "is-active" : ""} onClick={() => onDayChange(day.key)}><strong>{tabTitle(index)}</strong><span>{shortDate(day.date)}</span></button>)}</div>
    <section className="eiq-meetings-locked__filters" aria-label="Meeting filters"><div className="eiq-meetings-jurisdiction-filter"><span>Show</span>{(["ALL", "VIC", "WA", "HK"] as const).map((key) => <button key={key} type="button" className={jurisdictionFilter === key ? "is-active" : ""} onClick={() => setJurisdictionFilter(key)}>{key === "ALL" ? "All" : key}</button>)}</div><label className="is-search">Search meetings<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search meetings…" /></label>{(search || jurisdictionFilter !== "ALL") ? <button type="button" onClick={() => { setSearch(""); setJurisdictionFilter("ALL"); }}>Clear</button> : null}</section>
    <div className="eiq-meetings-jurisdictions">{grouped.map(({ key, meetings: jurisdictionMeetings }) => { const meta = JURISDICTIONS[key]; const raceCount = jurisdictionMeetings.reduce((sum, meeting) => sum + meeting.races, 0); return <section className="eiq-meetings-panel eiq-meetings-jurisdiction" key={key}><header className="eiq-meetings-jurisdiction__header"><div className="eiq-pra-identity" aria-label={`${meta.authority} identity`}><span className="eiq-pra-identity__fallback" title="Official authority logo asset pending approved repository asset">{meta.code}</span><div><strong>{meta.name}</strong><small>{meta.authority}</small></div></div><span>{jurisdictionMeetings.length} meeting{jurisdictionMeetings.length === 1 ? "" : "s"} · {raceCount} races</span></header><div className="eiq-meetings-locked__table-wrap"><table className="eiq-meetings-locked__table"><thead><tr><th>Meeting</th><th>State</th><th>Rail</th><th>Track Condition</th><th>Weather</th><th>First Race</th><th>Races</th><th>Scratchings</th><th /></tr></thead><tbody>{jurisdictionMeetings.map((meeting) => <tr key={meeting.meetingKey} className={meeting.meetingKey === selectedMeetingKey ? "is-selected" : ""} onClick={() => onSelectMeeting(meeting.rawMeeting)}><td><strong>{canonicalTrackDisplayName(meeting.meeting)}</strong></td><td>{display(meeting.state)}</td><td>{canonicalRailDisplay(meeting.rail)}</td><td>{canonicalTrackRatingDisplay(meeting.track)}</td><td>{canonicalWeatherDisplay(meeting.weather)}</td><td>{display(meeting.first)}</td><td>{meeting.races}</td><td>{meeting.scratchings ?? 0}</td><td><button type="button" disabled={detailLoading} onClick={(event) => { event.stopPropagation(); void openFirstRace(meeting); }}>View Races →</button></td></tr>)}</tbody></table></div></section>; })}{!grouped.length ? <div className="eiq-meetings-locked__empty">No meetings published for the selected date and filters.</div> : null}</div>
  </section>;
}
