import { useEffect, useMemo, useState } from "react";
import type { ThreeDayMeeting, ThreeDayRace } from "../services/threeDayCatalog";
import { canonicalRailDisplay, canonicalTrackDisplayName, canonicalTrackRatingDisplay, cleanProductText } from "../../design-system/presentation";
import { loadMeetingDetail, loadMeetingsWorkspaceViewModel, type MeetingSummaryViewModel, type MeetingsDayKey, type MeetingsWorkspaceViewModel } from "../services/meetingsFeed";
import { loadRaceDetail } from "../services/raceDetailFeed";
import { loadRacecourseWeatherFeed, meetingWeather, weatherDescription, type RacecourseWeatherRow } from "../services/racecourseWeatherFeed";

type MeetingsWorkspaceProps={selectedDayKey:MeetingsDayKey;selectedMeetingKey:string|null;clean:(value:any)=>string;onDayChange:(day:MeetingsDayKey)=>void;onSelectMeeting:(meeting:ThreeDayMeeting|null)=>void;onOpenMeeting:(meeting:ThreeDayMeeting)=>void;onOpenRace:(meeting:ThreeDayMeeting,race:ThreeDayRace,index:number)=>void};
type Jurisdiction="VIC"|"WA"|"HK"|"OTHER";
const display=(value:unknown,fallback="—")=>cleanProductText(value,fallback);
const JURISDICTIONS:Record<Jurisdiction,{name:string;code:string}>={VIC:{name:"Victoria",code:"VIC"},WA:{name:"Western Australia",code:"WA"},HK:{name:"Hong Kong",code:"HK"},OTHER:{name:"Other",code:"—"}};
function jurisdictionOf(m:MeetingSummaryViewModel):Jurisdiction{const state=display(m.state,"").toUpperCase(),name=canonicalTrackDisplayName(m.meeting).toUpperCase();if(state==="VIC"||state.includes("VICTORIA"))return"VIC";if(state==="WA"||state.includes("WESTERN AUSTRALIA"))return"WA";if(state==="HK"||state.includes("HONG KONG")||/SHA TIN|HAPPY VALLEY/.test(name))return"HK";return"OTHER"}
function shortDate(v:string){const[y,m,d]=v.split("-").map(Number);if(!y||!m||!d)return v;return new Intl.DateTimeFormat("en-AU",{weekday:"short",day:"numeric",month:"short",timeZone:"Australia/Melbourne"}).format(new Date(Date.UTC(y,m-1,d)))}
function tabTitle(i:number){return i===0?"Today":i===1?"Tomorrow":"Day +2"}
function bestTrack(...values:unknown[]){let broad="";for(const value of values){const rating=canonicalTrackRatingDisplay(value,"");if(!rating)continue;if(rating==="Synthetic"||/\d/.test(rating))return rating;if(!broad)broad=rating}return broad||"—"}

export function MeetingsWorkspace({selectedDayKey,selectedMeetingKey,onDayChange,onSelectMeeting,onOpenRace}:MeetingsWorkspaceProps){
 const[model,setModel]=useState<MeetingsWorkspaceViewModel|null>(null),[loading,setLoading]=useState(true),[detailLoading,setDetailLoading]=useState(false),[loadError,setLoadError]=useState(""),[search,setSearch]=useState(""),[jurisdictionFilter,setJurisdictionFilter]=useState<"ALL"|Jurisdiction>("ALL"),[details,setDetails]=useState<Record<string,ThreeDayMeeting>>({}),[weatherRows,setWeatherRows]=useState<RacecourseWeatherRow[]>([]);
 useEffect(()=>{let active=true;Promise.all([loadMeetingsWorkspaceViewModel(),loadRacecourseWeatherFeed().catch(()=>[])]).then(([next,w])=>{if(active){setModel(next);setWeatherRows(w);setLoading(false);setLoadError("")}}).catch(e=>{if(active){setModel(null);setLoading(false);setLoadError(e instanceof Error?e.message:"Meetings feed unavailable")}});return()=>{active=false}},[]);
 const activeDay=model?.days.find(d=>d.key===selectedDayKey)??model?.days[0]??null;
 useEffect(()=>{let active=true;if(!activeDay)return;Promise.all(activeDay.meetings.map(async m=>{try{return[m.meetingKey,await loadMeetingDetail(activeDay.date,m.meetingKey)] as const}catch{return null}})).then(rows=>{if(active)setDetails(Object.fromEntries(rows.filter((x):x is readonly[string,ThreeDayMeeting]=>Boolean(x))))});return()=>{active=false}},[activeDay]);
 const meetings=useMemo(()=>{const q=search.trim().toLowerCase();return(activeDay?.meetings??[]).filter(m=>{const j=jurisdictionOf(m),name=canonicalTrackDisplayName(m.meeting).toLowerCase();return(!q||name.includes(q))&&(jurisdictionFilter==="ALL"||j===jurisdictionFilter)})},[activeDay,search,jurisdictionFilter]);
 const totals=useMemo(()=>({meetings:meetings.length,races:meetings.reduce((s,m)=>s+m.races,0),runners:meetings.reduce((s,m)=>s+m.declared,0),scratchings:meetings.reduce((s,m)=>s+(m.scratchings??0),0)}),[meetings]);
 async function openFirstRace(m:MeetingSummaryViewModel){const r=m.raceSummaries[0];if(!r)return;setDetailLoading(true);try{const[md,rd]=await Promise.all([loadMeetingDetail(m.rawMeeting.date,m.meetingKey),loadRaceDetail(m.rawMeeting.date,m.meetingKey,r.raceKey)]);const merged={...md,races:md.races.map(x=>x.raceKey===r.raceKey?rd:x)};onSelectMeeting(merged);onOpenRace(merged,rd,0)}catch(e){setLoadError(e instanceof Error?e.message:"Race detail unavailable")}finally{setDetailLoading(false)}}
 if(loading)return <section className="eiq-meetings-locked"><div className="eiq-meetings-locked__empty">Loading meetings…</div></section>;
 return <section className="eiq-meetings-locked" aria-label="Meetings" data-edgeiq-workspace-key="MEETINGS">
  <header className="eiq-meetings-locked__header"><div><h1>Meetings</h1>{loadError?<p role="alert">{loadError}</p>:null}</div><div className="eiq-meetings-summary"><span><b>{totals.meetings}</b> Meetings</span><span><b>{totals.races}</b> Races</span><span><b>{totals.runners}</b> Runners</span><span><b>{totals.scratchings}</b> Scratchings</span></div></header>
  <div className="eiq-meetings-locked__days">{(model?.days??[]).slice(0,3).map((day,i)=><button key={day.key} className={day.key===activeDay?.key?"is-active":""} onClick={()=>onDayChange(day.key)}><strong>{tabTitle(i)}</strong><span>{shortDate(day.date)}</span><small>{day.totals.meetings} meeting{day.totals.meetings===1?"":"s"} · {day.totals.races} races</small></button>)}</div>
  <section className="eiq-meetings-locked__filters"><div className="eiq-meetings-jurisdiction-filter"><span>Jurisdiction</span>{(["ALL","VIC","WA","HK"] as const).map(key=><button key={key} className={jurisdictionFilter===key?"is-active":""} onClick={()=>setJurisdictionFilter(key)}>{key==="ALL"?"All":key}</button>)}</div><label className="is-search">Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search meetings…"/></label></section>
  <section className="eiq-meetings-panel eiq-meetings-board"><header><div><strong>{activeDay?shortDate(activeDay.date):"Meetings"}</strong><small>{totals.meetings} meeting{totals.meetings===1?"":"s"} · {totals.races} races</small></div></header><div className="eiq-meetings-locked__table-wrap"><table className="eiq-meetings-locked__table"><thead><tr><th>Meeting</th><th>State</th><th>First Race</th><th>Rail</th><th>Track</th><th>Weather</th><th>Races</th><th>Runners</th><th>Scratchings</th><th/></tr></thead><tbody>{meetings.map(m=>{const detail=details[m.meetingKey],first=detail?.races?.[0]?.raceTime||m.first,rail=detail?.rail||m.rail,track=bestTrack(detail?.trackCondition,m.track,...(detail?.races??[]).map(r=>r.trackCondition)),w=meetingWeather(weatherRows,m.meetingKey,activeDay?.date),meta=JURISDICTIONS[jurisdictionOf(m)];return <tr key={m.meetingKey} className={m.meetingKey===selectedMeetingKey?"is-selected":""} onClick={()=>onSelectMeeting(detail??m.rawMeeting)}><td><strong>{canonicalTrackDisplayName(m.meeting)}</strong></td><td><span className="eiq-jurisdiction-code">{meta.code}</span></td><td><strong>{display(first)}</strong></td><td>{canonicalRailDisplay(rail)}</td><td><span className="eiq-track-pill">{track}</span></td><td>{w?weatherDescription(w):display(m.weather)}</td><td>{m.races}</td><td>{m.declared}</td><td>{m.scratchings??0}</td><td><button disabled={detailLoading} onClick={e=>{e.stopPropagation();void openFirstRace(m)}}>View Races →</button></td></tr>})}{!meetings.length?<tr><td colSpan={10} className="eiq-meetings-locked__empty">No meetings match the current filters.</td></tr>:null}</tbody></table></div></section>
 </section>
}
